using Microsoft.EntityFrameworkCore;
using RustRconServerManager.Backend.Models;

namespace RustRconServerManager.Backend.Database;

/// <summary>
/// Seeder for the RustItems table. Contains all Rust game items for the give item functionality.
/// Data sourced from https://www.corrosionhour.com/rust-item-list/
/// </summary>
public static class RustItemSeeder
{
    public static async Task SeedAsync(AppDbContext context, ILogger? logger = null)
    {
        // Skip if items already exist
        if (await context.RustItems.AnyAsync())
        {
            return;
        }

        var items = GetRustItems();
        await context.RustItems.AddRangeAsync(items);
        await context.SaveChangesAsync();

        if (logger != null)
        {
            logger.LogInformation("[SEEDER] Seeded {Count} Rust items to the database.", items.Count);
        }
        else
        {
            Console.WriteLine($"[SEEDER] Seeded {items.Count} Rust items to the database.");
        }
    }

    private static List<RustItem> GetRustItems()
    {
        return new List<RustItem>
        {
            // Ammunition
            new() { DisplayName = "5.56 Rifle Ammo", ShortName = "ammo.rifle", ItemId = -1211166256, Description = "Standard rifle ammunition", StackSize = 128 },
            new() { DisplayName = "5.56 Rifle Ammo (Explosive)", ShortName = "ammo.rifle.explosive", ItemId = -1321651331, Description = "Explosive rifle ammunition", StackSize = 128 },
            new() { DisplayName = "5.56 Rifle Ammo (HV)", ShortName = "ammo.rifle.hv", ItemId = 1712070256, Description = "High velocity rifle ammunition", StackSize = 128 },
            new() { DisplayName = "5.56 Rifle Ammo (Incendiary)", ShortName = "ammo.rifle.incendiary", ItemId = 605467368, Description = "Incendiary rifle ammunition", StackSize = 128 },
            new() { DisplayName = "Pistol Bullet", ShortName = "ammo.pistol", ItemId = 785728077, Description = "Standard pistol ammunition", StackSize = 128 },
            new() { DisplayName = "Pistol Bullet (Fire)", ShortName = "ammo.pistol.fire", ItemId = 51984655, Description = "Incendiary pistol ammunition", StackSize = 128 },
            new() { DisplayName = "Pistol Bullet (HV)", ShortName = "ammo.pistol.hv", ItemId = -1691396643, Description = "High velocity pistol ammunition", StackSize = 128 },
            new() { DisplayName = "12 Gauge Buckshot", ShortName = "ammo.shotgun", ItemId = -1685290200, Description = "Standard shotgun ammunition", StackSize = 64 },
            new() { DisplayName = "12 Gauge Incendiary Shell", ShortName = "ammo.shotgun.fire", ItemId = -1036635990, Description = "Incendiary shotgun shell", StackSize = 64 },
            new() { DisplayName = "12 Gauge Slug", ShortName = "ammo.shotgun.slug", ItemId = -727717969, Description = "Solid shotgun slug", StackSize = 64 },
            new() { DisplayName = "Handmade Shell", ShortName = "ammo.handmade.shell", ItemId = 588596902, Description = "Crude handmade shotgun shell", StackSize = 64 },
            new() { DisplayName = "Nailgun Nails", ShortName = "ammo.nailgun.nails", ItemId = 1263920163, Description = "Nails for the nailgun", StackSize = 64 },
            new() { DisplayName = "Rocket", ShortName = "ammo.rocket.basic", ItemId = -742865266, Description = "Standard rocket", StackSize = 3 },
            new() { DisplayName = "High Velocity Rocket", ShortName = "ammo.rocket.hv", ItemId = 1638322904, Description = "Fast rocket with less damage", StackSize = 3 },
            new() { DisplayName = "Incendiary Rocket", ShortName = "ammo.rocket.fire", ItemId = 1578894260, Description = "Fire-starting rocket", StackSize = 3 },
            new() { DisplayName = "Smoke Rocket WIP!!!!", ShortName = "ammo.rocket.smoke", ItemId = -1841918730, Description = "Smoke rocket", StackSize = 3 },
            new() { DisplayName = "MLRS Rocket", ShortName = "ammo.rocket.mlrs", ItemId = -1843426638, Description = "MLRS artillery rocket", StackSize = 3 },
            new() { DisplayName = "40mm HE Grenade", ShortName = "ammo.grenadelauncher.he", ItemId = -1841918730, Description = "High explosive grenade launcher round", StackSize = 12 },
            new() { DisplayName = "40mm Shotgun Round", ShortName = "ammo.grenadelauncher.buckshot", ItemId = -1035059994, Description = "Shotgun round for grenade launcher", StackSize = 12 },
            new() { DisplayName = "40mm Smoke Grenade", ShortName = "ammo.grenadelauncher.smoke", ItemId = 915408809, Description = "Smoke grenade launcher round", StackSize = 12 },
            new() { DisplayName = "Arrow", ShortName = "arrow.wooden", ItemId = -1234735557, Description = "Wooden arrow", StackSize = 64 },
            new() { DisplayName = "Bone Arrow", ShortName = "arrow.bone", ItemId = 215754713, Description = "Arrow made from bone", StackSize = 64 },
            new() { DisplayName = "Fire Arrow", ShortName = "arrow.fire", ItemId = 14241751, Description = "Flaming arrow", StackSize = 64 },
            new() { DisplayName = "High Velocity Arrow", ShortName = "arrow.hv", ItemId = -1023065463, Description = "Fast flying arrow", StackSize = 64 },

            // Weapons
            new() { DisplayName = "Assault Rifle", ShortName = "rifle.ak", ItemId = 1545779598, Description = "Automatic assault rifle", StackSize = 1 },
            new() { DisplayName = "LR-300 Assault Rifle", ShortName = "rifle.lr300", ItemId = -1812555177, Description = "Military-grade assault rifle", StackSize = 1 },
            new() { DisplayName = "M249", ShortName = "lmg.m249", ItemId = -2069578888, Description = "Light machine gun", StackSize = 1 },
            new() { DisplayName = "Bolt Action Rifle", ShortName = "rifle.bolt", ItemId = 1588298435, Description = "High damage sniper rifle", StackSize = 1 },
            new() { DisplayName = "L96 Rifle", ShortName = "rifle.l96", ItemId = -778367295, Description = "Military sniper rifle", StackSize = 1 },
            new() { DisplayName = "M39 Rifle", ShortName = "rifle.m39", ItemId = 28201841, Description = "Semi-automatic marksman rifle", StackSize = 1 },
            new() { DisplayName = "Semi-Automatic Rifle", ShortName = "rifle.semiauto", ItemId = -904863145, Description = "Semi-automatic rifle", StackSize = 1 },
            new() { DisplayName = "Thompson", ShortName = "smg.thompson", ItemId = -1758372725, Description = "Submachine gun", StackSize = 1 },
            new() { DisplayName = "Custom SMG", ShortName = "smg.2", ItemId = 1796682209, Description = "Custom-made submachine gun", StackSize = 1 },
            new() { DisplayName = "MP5A4", ShortName = "smg.mp5", ItemId = 1318558775, Description = "Military submachine gun", StackSize = 1 },
            new() { DisplayName = "Pump Shotgun", ShortName = "shotgun.pump", ItemId = 795371088, Description = "Pump-action shotgun", StackSize = 1 },
            new() { DisplayName = "Spas-12 Shotgun", ShortName = "shotgun.spas12", ItemId = -41440462, Description = "Semi-automatic shotgun", StackSize = 1 },
            new() { DisplayName = "Double Barrel Shotgun", ShortName = "shotgun.double", ItemId = -765183617, Description = "Double barrel shotgun", StackSize = 1 },
            new() { DisplayName = "Waterpipe Shotgun", ShortName = "shotgun.waterpipe", ItemId = -1367281941, Description = "Crude pipe shotgun", StackSize = 1 },
            new() { DisplayName = "Eoka Pistol", ShortName = "pistol.eoka", ItemId = -75944661, Description = "Crude single-shot pistol", StackSize = 1 },
            new() { DisplayName = "Semi-Automatic Pistol", ShortName = "pistol.semiauto", ItemId = 818877484, Description = "Semi-automatic pistol", StackSize = 1 },
            new() { DisplayName = "Python Revolver", ShortName = "pistol.python", ItemId = 1373971859, Description = "High-powered revolver", StackSize = 1 },
            new() { DisplayName = "Revolver", ShortName = "pistol.revolver", ItemId = 649912614, Description = "Standard revolver", StackSize = 1 },
            new() { DisplayName = "M92 Pistol", ShortName = "pistol.m92", ItemId = -852563019, Description = "Military pistol", StackSize = 1 },
            new() { DisplayName = "Nailgun", ShortName = "pistol.nailgun", ItemId = 1953903201, Description = "Construction tool turned weapon", StackSize = 1 },
            new() { DisplayName = "Rocket Launcher", ShortName = "rocket.launcher", ItemId = 442886268, Description = "Fires rockets", StackSize = 1 },
            new() { DisplayName = "Multiple Grenade Launcher", ShortName = "multiplegrenadelauncher", ItemId = 1525520776, Description = "Fires multiple grenades", StackSize = 1 },
            new() { DisplayName = "Crossbow", ShortName = "crossbow", ItemId = 1965232394, Description = "Fires arrows", StackSize = 1 },
            new() { DisplayName = "Compound Bow", ShortName = "bow.compound", ItemId = 884424049, Description = "Advanced bow", StackSize = 1 },
            new() { DisplayName = "Hunting Bow", ShortName = "bow.hunting", ItemId = 1443579727, Description = "Standard bow", StackSize = 1 },
            new() { DisplayName = "Flame Thrower", ShortName = "flamethrower", ItemId = -1215753368, Description = "Projects fire", StackSize = 1 },
            new() { DisplayName = "Beancan Grenade", ShortName = "grenade.beancan", ItemId = -1308622549, Description = "Improvised grenade", StackSize = 5 },
            new() { DisplayName = "F1 Grenade", ShortName = "grenade.f1", ItemId = -1308622549, Description = "Fragmentation grenade", StackSize = 5 },
            new() { DisplayName = "Satchel Charge", ShortName = "explosive.satchel", ItemId = -1215166612, Description = "Improvised explosive", StackSize = 5 },
            new() { DisplayName = "Timed Explosive Charge", ShortName = "explosive.timed", ItemId = 1248356124, Description = "C4 explosive", StackSize = 5 },
            new() { DisplayName = "Survey Charge", ShortName = "surveycharge", ItemId = 1975934948, Description = "Reveals nearby resources", StackSize = 10 },

            // Melee Weapons
            new() { DisplayName = "Rock", ShortName = "rock", ItemId = 963906841, Description = "Basic starting tool", StackSize = 1 },
            new() { DisplayName = "Stone Spear", ShortName = "spear.stone", ItemId = 1602646136, Description = "Stone-tipped spear", StackSize = 1 },
            new() { DisplayName = "Wooden Spear", ShortName = "spear.wooden", ItemId = 1540879296, Description = "Wooden spear", StackSize = 1 },
            new() { DisplayName = "Bone Club", ShortName = "bone.club", ItemId = 1711323399, Description = "Club made from bone", StackSize = 1 },
            new() { DisplayName = "Bone Knife", ShortName = "knife.bone", ItemId = 1814288539, Description = "Knife made from bone", StackSize = 1 },
            new() { DisplayName = "Combat Knife", ShortName = "knife.combat", ItemId = 2040726127, Description = "Military combat knife", StackSize = 1 },
            new() { DisplayName = "Machete", ShortName = "machete", ItemId = -1137865085, Description = "Large cutting blade", StackSize = 1 },
            new() { DisplayName = "Salvaged Sword", ShortName = "salvaged.sword", ItemId = 1326180354, Description = "Makeshift sword", StackSize = 1 },
            new() { DisplayName = "Longsword", ShortName = "longsword", ItemId = -1469578201, Description = "Long blade sword", StackSize = 1 },
            new() { DisplayName = "Salvaged Cleaver", ShortName = "salvaged.cleaver", ItemId = -1978999529, Description = "Heavy cleaver", StackSize = 1 },
            new() { DisplayName = "Mace", ShortName = "mace", ItemId = 1001265731, Description = "Spiked mace", StackSize = 1 },
            new() { DisplayName = "Baseball Bat", ShortName = "mace.baseballbat", ItemId = -2026042603, Description = "Baseball bat", StackSize = 1 },
            new() { DisplayName = "Paddle", ShortName = "paddle", ItemId = -1708152885, Description = "Kayak paddle", StackSize = 1 },
            new() { DisplayName = "Pitchfork", ShortName = "pitchfork", ItemId = -1137865085, Description = "Farming pitchfork", StackSize = 1 },
            new() { DisplayName = "Sickle", ShortName = "sickle", ItemId = -1978999529, Description = "Farming sickle", StackSize = 1 },
            new() { DisplayName = "Butcher Knife", ShortName = "knife.butcher", ItemId = -194509282, Description = "Large butcher knife", StackSize = 1 },

            // Tools
            new() { DisplayName = "Stone Hatchet", ShortName = "stonehatchet", ItemId = -1583967946, Description = "Basic stone hatchet", StackSize = 1 },
            new() { DisplayName = "Stone Pickaxe", ShortName = "stone.pickaxe", ItemId = 171931394, Description = "Basic stone pickaxe", StackSize = 1 },
            new() { DisplayName = "Hatchet", ShortName = "hatchet", ItemId = -1252059217, Description = "Metal hatchet", StackSize = 1 },
            new() { DisplayName = "Pickaxe", ShortName = "pickaxe", ItemId = -1302129395, Description = "Metal pickaxe", StackSize = 1 },
            new() { DisplayName = "Salvaged Axe", ShortName = "axe.salvaged", ItemId = -262590403, Description = "Salvaged axe", StackSize = 1 },
            new() { DisplayName = "Salvaged Icepick", ShortName = "icepick.salvaged", ItemId = -1780802565, Description = "Salvaged icepick", StackSize = 1 },
            new() { DisplayName = "Salvaged Hammer", ShortName = "hammer.salvaged", ItemId = -1506397857, Description = "Salvaged hammer", StackSize = 1 },
            new() { DisplayName = "Jackhammer", ShortName = "jackhammer", ItemId = 1488979457, Description = "Powered mining tool", StackSize = 1 },
            new() { DisplayName = "Chainsaw", ShortName = "chainsaw", ItemId = 1104520648, Description = "Powered cutting tool", StackSize = 1 },
            new() { DisplayName = "Hammer", ShortName = "hammer", ItemId = 200773292, Description = "Building hammer", StackSize = 1 },
            new() { DisplayName = "Building Plan", ShortName = "building.planner", ItemId = -41896755, Description = "Building blueprint tool", StackSize = 1 },
            new() { DisplayName = "Torch", ShortName = "torch", ItemId = -1938052175, Description = "Handheld light source", StackSize = 1 },
            new() { DisplayName = "Flashlight", ShortName = "flashlight.held", ItemId = 596469572, Description = "Handheld flashlight", StackSize = 1 },
            new() { DisplayName = "Wire Tool", ShortName = "wiretool", ItemId = -144417939, Description = "Electrical wiring tool", StackSize = 1 },
            new() { DisplayName = "Hose Tool", ShortName = "hosetool", ItemId = 363467698, Description = "Water hose tool", StackSize = 1 },
            new() { DisplayName = "Spray Can", ShortName = "spraycan", ItemId = 1770475779, Description = "Spray paint tool", StackSize = 1 },
            new() { DisplayName = "Binoculars", ShortName = "tool.binoculars", ItemId = 1973684065, Description = "Long range viewing", StackSize = 1 },
            new() { DisplayName = "Geiger Counter", ShortName = "geiger.counter", ItemId = -1643076535, Description = "Radiation detector", StackSize = 1 },
            new() { DisplayName = "RF Pager", ShortName = "rf_pager", ItemId = -566907190, Description = "Radio frequency pager", StackSize = 1 },
            new() { DisplayName = "Supply Signal", ShortName = "supply.signal", ItemId = 1397052267, Description = "Calls supply drop", StackSize = 1 },

            // Building Materials
            new() { DisplayName = "Wood", ShortName = "wood", ItemId = -151838493, Description = "Basic building material", StackSize = 1000 },
            new() { DisplayName = "Stone", ShortName = "stones", ItemId = -892070738, Description = "Basic building material", StackSize = 1000 },
            new() { DisplayName = "Metal Fragments", ShortName = "metal.fragments", ItemId = 688032252, Description = "Refined metal", StackSize = 1000 },
            new() { DisplayName = "High Quality Metal", ShortName = "metal.refined", ItemId = 317398316, Description = "High quality metal", StackSize = 100 },
            new() { DisplayName = "Sulfur", ShortName = "sulfur", ItemId = -1581843485, Description = "Explosive component", StackSize = 1000 },
            new() { DisplayName = "Sulfur Ore", ShortName = "sulfur.ore", ItemId = -1157596551, Description = "Raw sulfur ore", StackSize = 1000 },
            new() { DisplayName = "Metal Ore", ShortName = "metal.ore", ItemId = -4031221, Description = "Raw metal ore", StackSize = 1000 },
            new() { DisplayName = "High Quality Metal Ore", ShortName = "hq.metal.ore", ItemId = -1982036270, Description = "High quality ore", StackSize = 100 },
            new() { DisplayName = "Charcoal", ShortName = "charcoal", ItemId = 1436001773, Description = "Fuel and gunpowder component", StackSize = 1000 },
            new() { DisplayName = "Gunpowder", ShortName = "gunpowder", ItemId = -265876753, Description = "Explosive powder", StackSize = 1000 },
            new() { DisplayName = "Explosives", ShortName = "explosives", ItemId = -592016202, Description = "Crafted explosive material", StackSize = 100 },
            new() { DisplayName = "Scrap", ShortName = "scrap", ItemId = -932201673, Description = "Currency and crafting material", StackSize = 1000 },
            new() { DisplayName = "Cloth", ShortName = "cloth", ItemId = -858312878, Description = "Fabric material", StackSize = 1000 },
            new() { DisplayName = "Leather", ShortName = "leather", ItemId = -946369541, Description = "Animal hide", StackSize = 1000 },
            new() { DisplayName = "Bone Fragments", ShortName = "bone.fragments", ItemId = 1719978075, Description = "Animal bones", StackSize = 1000 },
            new() { DisplayName = "Animal Fat", ShortName = "fat.animal", ItemId = -1978999529, Description = "Animal fat", StackSize = 1000 },
            new() { DisplayName = "Low Grade Fuel", ShortName = "lowgradefuel", ItemId = 28178745, Description = "Basic fuel", StackSize = 500 },
            new() { DisplayName = "Crude Oil", ShortName = "crude.oil", ItemId = -321733511, Description = "Raw oil", StackSize = 500 },
            new() { DisplayName = "Diesel Fuel", ShortName = "diesel_barrel", ItemId = 1568388703, Description = "Diesel fuel", StackSize = 20 },
            new() { DisplayName = "Tarp", ShortName = "tarp", ItemId = 2019042823, Description = "Tarp material", StackSize = 20 },
            new() { DisplayName = "Rope", ShortName = "rope", ItemId = -1035059994, Description = "Rope material", StackSize = 30 },
            new() { DisplayName = "Sewing Kit", ShortName = "sewingkit", ItemId = -419069863, Description = "Sewing supplies", StackSize = 10 },
            new() { DisplayName = "Empty Propane Tank", ShortName = "propanetank", ItemId = -1009492144, Description = "Empty propane tank", StackSize = 5 },
            new() { DisplayName = "Sheet Metal", ShortName = "sheetmetal", ItemId = -1211166256, Description = "Sheet metal", StackSize = 20 },
            new() { DisplayName = "Metal Pipe", ShortName = "metalpipe", ItemId = 95950017, Description = "Metal pipe", StackSize = 20 },
            new() { DisplayName = "Metal Blade", ShortName = "metalblade", ItemId = -1535621066, Description = "Metal blade", StackSize = 20 },
            new() { DisplayName = "Metal Spring", ShortName = "metalspring", ItemId = -1021495308, Description = "Metal spring", StackSize = 20 },
            new() { DisplayName = "Gears", ShortName = "gears", ItemId = -1549739227, Description = "Mechanical gears", StackSize = 20 },
            new() { DisplayName = "Road Signs", ShortName = "roadsigns", ItemId = -1535621066, Description = "Road signs", StackSize = 5 },
            new() { DisplayName = "Rifle Body", ShortName = "riflebody", ItemId = -2097376851, Description = "Rifle receiver", StackSize = 1 },
            new() { DisplayName = "SMG Body", ShortName = "smgbody", ItemId = -1474093279, Description = "SMG receiver", StackSize = 1 },
            new() { DisplayName = "Semi Automatic Body", ShortName = "semibody", ItemId = 1581210395, Description = "Semi-auto receiver", StackSize = 1 },
            new() { DisplayName = "Tech Trash", ShortName = "techparts", ItemId = -1471379076, Description = "Electronic components", StackSize = 50 },
            new() { DisplayName = "CCTV Camera", ShortName = "cctv.camera", ItemId = 634478325, Description = "Surveillance camera", StackSize = 5 },
            new() { DisplayName = "Targeting Computer", ShortName = "targeting.computer", ItemId = 1523195708, Description = "Auto turret targeting", StackSize = 1 },

            // Medical
            new() { DisplayName = "Bandage", ShortName = "bandage", ItemId = -2072273936, Description = "Stops bleeding", StackSize = 3 },
            new() { DisplayName = "Medical Syringe", ShortName = "syringe.medical", ItemId = 1079279582, Description = "Instant health boost", StackSize = 5 },
            new() { DisplayName = "Large Medkit", ShortName = "largemedkit", ItemId = 254522515, Description = "Large health restoration", StackSize = 1 },
            new() { DisplayName = "Anti-Radiation Pills", ShortName = "antiradpills", ItemId = -132516482, Description = "Reduces radiation", StackSize = 10 },
            new() { DisplayName = "Blood", ShortName = "blood", ItemId = -1063412582, Description = "Blood for transfusion", StackSize = 50 },

            // Food
            new() { DisplayName = "Apple", ShortName = "apple", ItemId = -586784898, Description = "Healthy apple", StackSize = 10 },
            new() { DisplayName = "Blueberries", ShortName = "blueberries", ItemId = -1986896580, Description = "Wild blueberries", StackSize = 20 },
            new() { DisplayName = "Raw Chicken Breast", ShortName = "chicken.raw", ItemId = -726947205, Description = "Raw chicken meat", StackSize = 10 },
            new() { DisplayName = "Cooked Chicken", ShortName = "chicken.cooked", ItemId = -1848736516, Description = "Cooked chicken", StackSize = 10 },
            new() { DisplayName = "Burned Chicken", ShortName = "chicken.burned", ItemId = 889398893, Description = "Overcooked chicken", StackSize = 10 },
            new() { DisplayName = "Spoiled Chicken", ShortName = "chicken.spoiled", ItemId = -225234813, Description = "Rotten chicken", StackSize = 10 },
            new() { DisplayName = "Raw Deer Meat", ShortName = "deermeat.raw", ItemId = -202239044, Description = "Raw deer meat", StackSize = 10 },
            new() { DisplayName = "Cooked Deer Meat", ShortName = "deermeat.cooked", ItemId = -533875561, Description = "Cooked deer meat", StackSize = 10 },
            new() { DisplayName = "Burned Deer Meat", ShortName = "deermeat.burned", ItemId = 173268132, Description = "Burned deer meat", StackSize = 10 },
            new() { DisplayName = "Raw Fish", ShortName = "fish.raw", ItemId = -1779183908, Description = "Raw fish", StackSize = 10 },
            new() { DisplayName = "Cooked Fish", ShortName = "fish.cooked", ItemId = -979706915, Description = "Cooked fish", StackSize = 10 },
            new() { DisplayName = "Raw Horse Meat", ShortName = "horsemeat.raw", ItemId = 264729749, Description = "Raw horse meat", StackSize = 10 },
            new() { DisplayName = "Cooked Horse Meat", ShortName = "horsemeat.cooked", ItemId = -1966381470, Description = "Cooked horse meat", StackSize = 10 },
            new() { DisplayName = "Raw Human Meat", ShortName = "humanmeat.raw", ItemId = 1325935999, Description = "Raw human meat", StackSize = 10 },
            new() { DisplayName = "Cooked Human Meat", ShortName = "humanmeat.cooked", ItemId = -991829475, Description = "Cooked human meat", StackSize = 10 },
            new() { DisplayName = "Raw Pork", ShortName = "meat.boar", ItemId = -253819519, Description = "Raw boar meat", StackSize = 10 },
            new() { DisplayName = "Cooked Pork", ShortName = "meat.pork.cooked", ItemId = 1712070256, Description = "Cooked pork", StackSize = 10 },
            new() { DisplayName = "Burned Pork", ShortName = "meat.pork.burned", ItemId = -1941067051, Description = "Burned pork", StackSize = 10 },
            new() { DisplayName = "Raw Bear Meat", ShortName = "bearmeat", ItemId = 476066818, Description = "Raw bear meat", StackSize = 10 },
            new() { DisplayName = "Cooked Bear Meat", ShortName = "bearmeat.cooked", ItemId = -1754948969, Description = "Cooked bear meat", StackSize = 10 },
            new() { DisplayName = "Burned Bear Meat", ShortName = "bearmeat.burned", ItemId = -1545084634, Description = "Burned bear meat", StackSize = 10 },
            new() { DisplayName = "Raw Wolf Meat", ShortName = "wolfmeat.raw", ItemId = -1691991080, Description = "Raw wolf meat", StackSize = 10 },
            new() { DisplayName = "Cooked Wolf Meat", ShortName = "wolfmeat.cooked", ItemId = 1390353317, Description = "Cooked wolf meat", StackSize = 10 },
            new() { DisplayName = "Burned Wolf Meat", ShortName = "wolfmeat.burned", ItemId = -1598790097, Description = "Burned wolf meat", StackSize = 10 },
            new() { DisplayName = "Corn", ShortName = "corn", ItemId = -2073307447, Description = "Fresh corn", StackSize = 20 },
            new() { DisplayName = "Grub", ShortName = "grub", ItemId = -1667839928, Description = "Edible grub", StackSize = 10 },
            new() { DisplayName = "Mushroom", ShortName = "mushroom", ItemId = -1598339559, Description = "Edible mushroom", StackSize = 20 },
            new() { DisplayName = "Potato", ShortName = "potato", ItemId = 803954639, Description = "Raw potato", StackSize = 20 },
            new() { DisplayName = "Pumpkin", ShortName = "pumpkin", ItemId = -225234813, Description = "Fresh pumpkin", StackSize = 20 },
            new() { DisplayName = "Black Raspberries", ShortName = "black.raspberries", ItemId = -23467166, Description = "Wild raspberries", StackSize = 20 },
            new() { DisplayName = "Chocolate Bar", ShortName = "chocholate", ItemId = -1861522751, Description = "Chocolate bar", StackSize = 5 },
            new() { DisplayName = "Granola Bar", ShortName = "granolabar", ItemId = -465682601, Description = "Energy bar", StackSize = 10 },
            new() { DisplayName = "Can of Beans", ShortName = "can.beans", ItemId = -1002156085, Description = "Canned beans", StackSize = 10 },
            new() { DisplayName = "Can of Tuna", ShortName = "can.tuna", ItemId = 567235583, Description = "Canned tuna", StackSize = 10 },
            new() { DisplayName = "Pickles", ShortName = "jar.pickle", ItemId = -316250604, Description = "Jar of pickles", StackSize = 3 },

            // Drinks
            new() { DisplayName = "Water", ShortName = "water", ItemId = -1779180711, Description = "Drinking water", StackSize = 1 },
            new() { DisplayName = "Salt Water", ShortName = "water.salt", ItemId = -277057363, Description = "Salt water", StackSize = 1 },
            new() { DisplayName = "Small Water Bottle", ShortName = "smallwaterbottle", ItemId = 1885488976, Description = "Small water container", StackSize = 1 },
            new() { DisplayName = "Water Jug", ShortName = "waterjug", ItemId = 1817873886, Description = "Large water container", StackSize = 1 },
            new() { DisplayName = "Bota Bag", ShortName = "botabag", ItemId = 613961768, Description = "Leather water bag", StackSize = 1 },
            new() { DisplayName = "Apple Juice", ShortName = "apple.juice", ItemId = -586784898, Description = "Apple juice", StackSize = 10 },
            new() { DisplayName = "Pumpkin Juice", ShortName = "pumpkin.juice", ItemId = -225234813, Description = "Pumpkin juice", StackSize = 10 },

            // Clothing - Head
            new() { DisplayName = "Bandana Mask", ShortName = "mask.bandana", ItemId = -1588628467, Description = "Face covering", StackSize = 1 },
            new() { DisplayName = "Boonie Hat", ShortName = "hat.boonie", ItemId = -1138648591, Description = "Wide-brim hat", StackSize = 1 },
            new() { DisplayName = "Bucket Helmet", ShortName = "bucket.helmet", ItemId = 1260209393, Description = "Makeshift helmet", StackSize = 1 },
            new() { DisplayName = "Burlap Headwrap", ShortName = "burlap.headwrap", ItemId = -459156023, Description = "Basic head wrap", StackSize = 1 },
            new() { DisplayName = "Candle Hat", ShortName = "hat.candle", ItemId = -936921910, Description = "Hat with candle", StackSize = 1 },
            new() { DisplayName = "Coffee Can Helmet", ShortName = "coffeecan.helmet", ItemId = -1958316066, Description = "Armored helmet", StackSize = 1 },
            new() { DisplayName = "Deer Skull Mask", ShortName = "deer.skull.mask", ItemId = -1720378890, Description = "Skull mask", StackSize = 1 },
            new() { DisplayName = "Heavy Plate Helmet", ShortName = "heavy.plate.helmet", ItemId = -1334615971, Description = "Heavy armor helmet", StackSize = 1 },
            new() { DisplayName = "Metal Facemask", ShortName = "metal.facemask", ItemId = -46188931, Description = "Metal face protection", StackSize = 1 },
            new() { DisplayName = "Miners Hat", ShortName = "hat.miner", ItemId = -1211618504, Description = "Hat with light", StackSize = 1 },
            new() { DisplayName = "Riot Helmet", ShortName = "riot.helmet", ItemId = -1101924344, Description = "Riot control helmet", StackSize = 1 },
            new() { DisplayName = "Wolf Headdress", ShortName = "wolf.headdress", ItemId = 431617507, Description = "Wolf skull hat", StackSize = 1 },
            new() { DisplayName = "Wood Armor Helmet", ShortName = "wood.armor.helmet", ItemId = 107868, Description = "Wooden helmet", StackSize = 1 },

            // Clothing - Chest
            new() { DisplayName = "Bone Armor", ShortName = "bone.armor.suit", ItemId = 2105486942, Description = "Bone plate armor", StackSize = 1 },
            new() { DisplayName = "Burlap Shirt", ShortName = "burlap.shirt", ItemId = -566907190, Description = "Basic shirt", StackSize = 1 },
            new() { DisplayName = "Heavy Plate Jacket", ShortName = "heavy.plate.jacket", ItemId = 69511070, Description = "Heavy armor jacket", StackSize = 1 },
            new() { DisplayName = "Hide Poncho", ShortName = "attire.hide.poncho", ItemId = 2045246801, Description = "Hide poncho", StackSize = 1 },
            new() { DisplayName = "Hide Vest", ShortName = "attire.hide.vest", ItemId = 1751045826, Description = "Hide vest", StackSize = 1 },
            new() { DisplayName = "Hoodie", ShortName = "hoodie", ItemId = 1266491000, Description = "Hooded sweatshirt", StackSize = 1 },
            new() { DisplayName = "Jacket", ShortName = "jacket", ItemId = -1163532624, Description = "Jacket", StackSize = 1 },
            new() { DisplayName = "Leather Vest", ShortName = "jacket.vagabond", ItemId = -1163532624, Description = "Leather vest", StackSize = 1 },
            new() { DisplayName = "Longsleeve T-Shirt", ShortName = "tshirt.long", ItemId = 223891266, Description = "Long sleeve shirt", StackSize = 1 },
            new() { DisplayName = "Metal Chest Plate", ShortName = "metal.plate.torso", ItemId = 1110385766, Description = "Metal torso armor", StackSize = 1 },
            new() { DisplayName = "Road Sign Jacket", ShortName = "roadsign.jacket", ItemId = 1877339384, Description = "Road sign armor", StackSize = 1 },
            new() { DisplayName = "Shirt", ShortName = "shirt.collared", ItemId = -1659202509, Description = "Collared shirt", StackSize = 1 },
            new() { DisplayName = "Snow Jacket", ShortName = "jacket.snow", ItemId = 1330084809, Description = "Winter jacket", StackSize = 1 },
            new() { DisplayName = "Tank Top", ShortName = "shirt.tanktop", ItemId = -702051347, Description = "Tank top", StackSize = 1 },
            new() { DisplayName = "T-Shirt", ShortName = "tshirt", ItemId = -1659202509, Description = "T-shirt", StackSize = 1 },
            new() { DisplayName = "Wood Chestplate", ShortName = "wood.armor.jacket", ItemId = -1583967946, Description = "Wooden chest armor", StackSize = 1 },

            // Clothing - Legs
            new() { DisplayName = "Burlap Trousers", ShortName = "burlap.trousers", ItemId = -1978999529, Description = "Basic pants", StackSize = 1 },
            new() { DisplayName = "Heavy Plate Pants", ShortName = "heavy.plate.pants", ItemId = -2001260025, Description = "Heavy armor pants", StackSize = 1 },
            new() { DisplayName = "Hide Pants", ShortName = "attire.hide.pants", ItemId = -852563019, Description = "Hide pants", StackSize = 1 },
            new() { DisplayName = "Hide Skirt", ShortName = "attire.hide.skirt", ItemId = 1850456855, Description = "Hide skirt", StackSize = 1 },
            new() { DisplayName = "Pants", ShortName = "pants", ItemId = 106433500, Description = "Regular pants", StackSize = 1 },
            new() { DisplayName = "Road Sign Kilt", ShortName = "roadsign.kilt", ItemId = 237239288, Description = "Road sign leg armor", StackSize = 1 },
            new() { DisplayName = "Shorts", ShortName = "pants.shorts", ItemId = 1850456855, Description = "Short pants", StackSize = 1 },
            new() { DisplayName = "Wood Armor Pants", ShortName = "wood.armor.pants", ItemId = -685265909, Description = "Wooden leg armor", StackSize = 1 },

            // Clothing - Feet
            new() { DisplayName = "Boots", ShortName = "shoes.boots", ItemId = -1549739227, Description = "Leather boots", StackSize = 1 },
            new() { DisplayName = "Burlap Shoes", ShortName = "burlap.shoes", ItemId = -1025578387, Description = "Basic shoes", StackSize = 1 },
            new() { DisplayName = "Hide Boots", ShortName = "attire.hide.boots", ItemId = 794443127, Description = "Hide boots", StackSize = 1 },

            // Clothing - Hands
            new() { DisplayName = "Burlap Gloves", ShortName = "burlap.gloves", ItemId = 1659114910, Description = "Basic gloves", StackSize = 1 },
            new() { DisplayName = "Hide Gloves", ShortName = "attire.hide.gloves", ItemId = 1080289915, Description = "Hide gloves", StackSize = 1 },
            new() { DisplayName = "Leather Gloves", ShortName = "burlap.gloves.new", ItemId = -522149009, Description = "Leather gloves", StackSize = 1 },
            new() { DisplayName = "Roadsign Gloves", ShortName = "roadsign.gloves", ItemId = 1850456855, Description = "Armored gloves", StackSize = 1 },
            new() { DisplayName = "Tactical Gloves", ShortName = "tactical.gloves", ItemId = 1659114910, Description = "Tactical gloves", StackSize = 1 },

            // Hazmat Suits
            new() { DisplayName = "Hazmat Suit", ShortName = "hazmatsuit", ItemId = -1323101799, Description = "Radiation protection suit", StackSize = 1 },
            new() { DisplayName = "Hazmat Suit (Arctic)", ShortName = "hazmatsuit.arcticcamo", ItemId = 1749787215, Description = "Arctic hazmat suit", StackSize = 1 },
            new() { DisplayName = "Hazmat Suit (Spacesuit)", ShortName = "hazmatsuit.spacesuit", ItemId = 1051155022, Description = "Space hazmat suit", StackSize = 1 },

            // Deployables
            new() { DisplayName = "Sleeping Bag", ShortName = "sleepingbag", ItemId = 1253290621, Description = "Spawn point", StackSize = 1 },
            new() { DisplayName = "Bed", ShortName = "bed", ItemId = -1273339005, Description = "Comfortable spawn point", StackSize = 1 },
            new() { DisplayName = "Beach Towel", ShortName = "beachtowel", ItemId = 1230323789, Description = "Beach spawn point", StackSize = 1 },
            new() { DisplayName = "Small Stash", ShortName = "stash.small", ItemId = -369760990, Description = "Hidden storage", StackSize = 1 },
            new() { DisplayName = "Wood Storage Box", ShortName = "box.wooden", ItemId = -770311783, Description = "Small storage", StackSize = 1 },
            new() { DisplayName = "Large Wood Box", ShortName = "box.wooden.large", ItemId = 2066926276, Description = "Large storage", StackSize = 1 },
            new() { DisplayName = "Coffin", ShortName = "coffin.storage", ItemId = 1849912854, Description = "Coffin storage", StackSize = 1 },
            new() { DisplayName = "Locker", ShortName = "locker", ItemId = 177226991, Description = "Personal storage", StackSize = 1 },
            new() { DisplayName = "Fridge", ShortName = "fridge", ItemId = 1844023509, Description = "Food storage", StackSize = 1 },
            new() { DisplayName = "Tool Cupboard", ShortName = "cupboard.tool", ItemId = -97956382, Description = "Building privilege", StackSize = 1 },
            new() { DisplayName = "Workbench Level 1", ShortName = "workbench1", ItemId = -1607980696, Description = "Tier 1 crafting", StackSize = 1 },
            new() { DisplayName = "Workbench Level 2", ShortName = "workbench2", ItemId = -41896755, Description = "Tier 2 crafting", StackSize = 1 },
            new() { DisplayName = "Workbench Level 3", ShortName = "workbench3", ItemId = 1524187186, Description = "Tier 3 crafting", StackSize = 1 },
            new() { DisplayName = "Repair Bench", ShortName = "box.repair.bench", ItemId = -586342290, Description = "Item repair station", StackSize = 1 },
            new() { DisplayName = "Research Table", ShortName = "research.table", ItemId = -1130350963, Description = "Blueprint research", StackSize = 1 },
            new() { DisplayName = "Mixing Table", ShortName = "mixing.table", ItemId = -2043730634, Description = "Tea mixing station", StackSize = 1 },
            new() { DisplayName = "Small Furnace", ShortName = "furnace", ItemId = -1157596551, Description = "Smelting furnace", StackSize = 1 },
            new() { DisplayName = "Large Furnace", ShortName = "furnace.large", ItemId = -1992717673, Description = "Large smelting furnace", StackSize = 1 },
            new() { DisplayName = "Camp Fire", ShortName = "campfire", ItemId = -1461508848, Description = "Cooking fire", StackSize = 1 },
            new() { DisplayName = "BBQ", ShortName = "bbq", ItemId = -1021495308, Description = "Outdoor grill", StackSize = 1 },
            new() { DisplayName = "Skull Fire Pit", ShortName = "skull_fire_pit", ItemId = -1628526499, Description = "Decorative fire pit", StackSize = 1 },
            new() { DisplayName = "Small Oil Refinery", ShortName = "small.oil.refinery", ItemId = 708573406, Description = "Oil processing", StackSize = 1 },
            new() { DisplayName = "Recycler", ShortName = "recycler", ItemId = 61462323, Description = "Item recycling", StackSize = 1 },
            new() { DisplayName = "Auto Turret", ShortName = "autoturret", ItemId = -2139580305, Description = "Automated defense", StackSize = 1 },
            new() { DisplayName = "Flame Turret", ShortName = "flameturret", ItemId = -1009492144, Description = "Fire defense", StackSize = 1 },
            new() { DisplayName = "Shotgun Trap", ShortName = "guntrap", ItemId = -1123473824, Description = "Shotgun defense", StackSize = 1 },
            new() { DisplayName = "Landmine", ShortName = "landmine", ItemId = 255101535, Description = "Explosive trap", StackSize = 5 },
            new() { DisplayName = "Bear Trap", ShortName = "trap.bear", ItemId = -1679267738, Description = "Leg trap", StackSize = 3 },
            new() { DisplayName = "Snap Trap", ShortName = "snaptrap", ItemId = -220573904, Description = "Small trap", StackSize = 10 },
            new() { DisplayName = "SAM Site", ShortName = "samsite", ItemId = -1009492144, Description = "Anti-air defense", StackSize = 1 },
            new() { DisplayName = "Tesla Coil", ShortName = "electric.teslacoil", ItemId = 1371909803, Description = "Electric defense", StackSize = 1 },
            new() { DisplayName = "Search Light", ShortName = "searchlight", ItemId = 1153652756, Description = "Spotlight", StackSize = 1 },
            new() { DisplayName = "Ceiling Light", ShortName = "ceilinglight", ItemId = -1044468317, Description = "Ceiling lamp", StackSize = 1 },
            new() { DisplayName = "Lantern", ShortName = "lantern", ItemId = -1097452776, Description = "Portable light", StackSize = 1 },
            new() { DisplayName = "Chinese Lantern", ShortName = "chineselantern", ItemId = -1044400758, Description = "Decorative lantern", StackSize = 1 },
            new() { DisplayName = "Jack O Lantern Happy", ShortName = "jackolantern.happy", ItemId = -583379016, Description = "Happy pumpkin", StackSize = 1 },
            new() { DisplayName = "Jack O Lantern Angry", ShortName = "jackolantern.angry", ItemId = -1632568512, Description = "Angry pumpkin", StackSize = 1 },
            new() { DisplayName = "Tuna Can Lamp", ShortName = "tunalight", ItemId = -596876839, Description = "Small lamp", StackSize = 1 },

            // Doors
            new() { DisplayName = "Wooden Door", ShortName = "door.hinged.wood", ItemId = 1456441506, Description = "Wood door", StackSize = 1 },
            new() { DisplayName = "Sheet Metal Door", ShortName = "door.hinged.metal", ItemId = -1571725662, Description = "Metal door", StackSize = 1 },
            new() { DisplayName = "Armored Door", ShortName = "door.hinged.toptier", ItemId = -1336109173, Description = "Armored door", StackSize = 1 },
            new() { DisplayName = "Wood Double Door", ShortName = "door.double.hinged.wood", ItemId = 1873897110, Description = "Double wood door", StackSize = 1 },
            new() { DisplayName = "Sheet Metal Double Door", ShortName = "door.double.hinged.metal", ItemId = -148163128, Description = "Double metal door", StackSize = 1 },
            new() { DisplayName = "Armored Double Door", ShortName = "door.double.hinged.toptier", ItemId = -933236257, Description = "Double armored door", StackSize = 1 },
            new() { DisplayName = "Garage Door", ShortName = "wall.frame.garagedoor", ItemId = -190707220, Description = "Garage door", StackSize = 1 },
            new() { DisplayName = "Ladder Hatch", ShortName = "floor.ladder.hatch", ItemId = -132247350, Description = "Floor hatch", StackSize = 1 },
            new() { DisplayName = "Triangle Ladder Hatch", ShortName = "floor.triangle.ladder.hatch", ItemId = -1152899733, Description = "Triangle floor hatch", StackSize = 1 },
            new() { DisplayName = "Prison Cell Gate", ShortName = "wall.frame.cell.gate", ItemId = 1859976884, Description = "Prison gate", StackSize = 1 },
            new() { DisplayName = "Chainlink Fence Gate", ShortName = "wall.frame.fence.gate", ItemId = -427925529, Description = "Fence gate", StackSize = 1 },

            // Locks
            new() { DisplayName = "Key Lock", ShortName = "lock.key", ItemId = -850982208, Description = "Key-based lock", StackSize = 1 },
            new() { DisplayName = "Code Lock", ShortName = "lock.code", ItemId = 1159991980, Description = "Code-based lock", StackSize = 1 },

            // Barricades
            new() { DisplayName = "Wooden Barricade", ShortName = "barricade.wood", ItemId = -814689390, Description = "Wood barrier", StackSize = 5 },
            new() { DisplayName = "Metal Barricade", ShortName = "barricade.metal", ItemId = -139986104, Description = "Metal barrier", StackSize = 3 },
            new() { DisplayName = "Stone Barricade", ShortName = "barricade.stone", ItemId = 1175970197, Description = "Stone barrier", StackSize = 3 },
            new() { DisplayName = "Barbed Wooden Barricade", ShortName = "barricade.woodwire", ItemId = -814689390, Description = "Barbed wood barrier", StackSize = 3 },
            new() { DisplayName = "Sandbag Barricade", ShortName = "barricade.sandbags", ItemId = 1608640313, Description = "Sandbag cover", StackSize = 3 },
            new() { DisplayName = "Concrete Barricade", ShortName = "barricade.concrete", ItemId = 1608640313, Description = "Concrete barrier", StackSize = 3 },

            // High External Walls
            new() { DisplayName = "High External Stone Wall", ShortName = "wall.external.high.stone", ItemId = -1019962023, Description = "Large stone wall", StackSize = 10 },
            new() { DisplayName = "High External Wood Wall", ShortName = "wall.external.high", ItemId = 1745077396, Description = "Large wood wall", StackSize = 10 },
            new() { DisplayName = "High External Stone Gate", ShortName = "gates.external.high.stone", ItemId = -1685290200, Description = "Stone gate", StackSize = 1 },
            new() { DisplayName = "High External Wood Gate", ShortName = "gates.external.high.wood", ItemId = 686589492, Description = "Wood gate", StackSize = 1 },

            // Electrical
            new() { DisplayName = "Small Generator", ShortName = "electric.generator.small", ItemId = -1673693549, Description = "Power generator", StackSize = 1 },
            new() { DisplayName = "Wind Turbine", ShortName = "generator.wind.scrap", ItemId = 1849912854, Description = "Wind power", StackSize = 1 },
            new() { DisplayName = "Solar Panel", ShortName = "solar.panel.large", ItemId = -965682070, Description = "Solar power", StackSize = 1 },
            new() { DisplayName = "Small Battery", ShortName = "electric.battery.small", ItemId = 1625090418, Description = "Power storage", StackSize = 1 },
            new() { DisplayName = "Medium Battery", ShortName = "electric.battery.medium", ItemId = -454226205, Description = "Medium power storage", StackSize = 1 },
            new() { DisplayName = "Large Battery", ShortName = "electric.battery.large", ItemId = 553270375, Description = "Large power storage", StackSize = 1 },
            new() { DisplayName = "Switch", ShortName = "electric.switch", ItemId = -220573904, Description = "Power switch", StackSize = 5 },
            new() { DisplayName = "Timer", ShortName = "electric.timer", ItemId = 665332906, Description = "Timed switch", StackSize = 3 },
            new() { DisplayName = "Splitter", ShortName = "electric.splitter", ItemId = -561148628, Description = "Power splitter", StackSize = 5 },
            new() { DisplayName = "Blocker", ShortName = "electric.blocker", ItemId = 486166145, Description = "Power blocker", StackSize = 5 },
            new() { DisplayName = "Electrical Branch", ShortName = "electrical.branch", ItemId = -1448252298, Description = "Power branch", StackSize = 5 },
            new() { DisplayName = "Root Combiner", ShortName = "electrical.combiner", ItemId = -1588628467, Description = "Power combiner", StackSize = 5 },
            new() { DisplayName = "Counter", ShortName = "electric.counter", ItemId = -216999575, Description = "Power counter", StackSize = 3 },
            new() { DisplayName = "RF Transmitter", ShortName = "electric.rf.transmitter", ItemId = 596469572, Description = "RF signal sender", StackSize = 3 },
            new() { DisplayName = "RF Receiver", ShortName = "electric.rf.receiver", ItemId = 596469572, Description = "RF signal receiver", StackSize = 3 },
            new() { DisplayName = "RF Broadcaster", ShortName = "electric.rf.broadcaster", ItemId = -784870680, Description = "RF broadcaster", StackSize = 1 },
            new() { DisplayName = "Smart Alarm", ShortName = "smart.alarm", ItemId = -695978112, Description = "Smart alert system", StackSize = 3 },
            new() { DisplayName = "Smart Switch", ShortName = "smart.switch", ItemId = 98228420, Description = "Remote switch", StackSize = 3 },
            new() { DisplayName = "Laser Detector", ShortName = "electric.laserdetector", ItemId = -1962139795, Description = "Laser tripwire", StackSize = 5 },
            new() { DisplayName = "Pressure Pad", ShortName = "electric.pressurepad", ItemId = -2103694546, Description = "Pressure sensor", StackSize = 5 },
            new() { DisplayName = "HBHF Sensor", ShortName = "electric.hbhfsensor", ItemId = -1138208076, Description = "Heartbeat sensor", StackSize = 3 },
            new() { DisplayName = "Simple Light", ShortName = "electric.simplelight", ItemId = 350142668, Description = "Basic light", StackSize = 5 },
            new() { DisplayName = "Siren Light", ShortName = "electric.sirenlight", ItemId = -1530414552, Description = "Warning light", StackSize = 3 },
            new() { DisplayName = "Flasher Light", ShortName = "electric.flasherlight", ItemId = 1849912854, Description = "Flashing light", StackSize = 3 },
            new() { DisplayName = "Door Controller", ShortName = "electric.doorcontroller", ItemId = -1598387132, Description = "Powered door control", StackSize = 3 },
            new() { DisplayName = "Igniter", ShortName = "electric.igniter", ItemId = 853471967, Description = "Electric igniter", StackSize = 5 },
            new() { DisplayName = "Powered Water Purifier", ShortName = "powered.water.purifier", ItemId = 1651220691, Description = "Electric purifier", StackSize = 1 },
            new() { DisplayName = "Elevator", ShortName = "elevator", ItemId = -1549739227, Description = "Vertical transport", StackSize = 1 },
            new() { DisplayName = "Modular Car Lift", ShortName = "modularcarlift", ItemId = -1102888940, Description = "Vehicle lift", StackSize = 1 },

            // Industrial
            new() { DisplayName = "Industrial Conveyor", ShortName = "industrial.conveyor", ItemId = -1958316066, Description = "Item transport", StackSize = 5 },
            new() { DisplayName = "Industrial Combiner", ShortName = "industrial.combiner", ItemId = 1217343498, Description = "Item combiner", StackSize = 3 },
            new() { DisplayName = "Industrial Splitter", ShortName = "industrial.splitter", ItemId = -559599960, Description = "Item splitter", StackSize = 3 },
            new() { DisplayName = "Industrial Crafter", ShortName = "industrial.crafter", ItemId = 1918357871, Description = "Auto crafter", StackSize = 1 },
            new() { DisplayName = "Storage Adaptor", ShortName = "industrial.storage.adaptor", ItemId = -268547355, Description = "Storage interface", StackSize = 5 },
            new() { DisplayName = "Industrial Wall Light", ShortName = "industrial.wall.lamp", ItemId = 1178406703, Description = "Industrial lamp", StackSize = 5 },
            new() { DisplayName = "Industrial Door", ShortName = "industrial.door", ItemId = 1598149413, Description = "Industrial door", StackSize = 1 },

            // Water
            new() { DisplayName = "Water Barrel", ShortName = "water.barrel", ItemId = -1863559151, Description = "Water storage", StackSize = 1 },
            new() { DisplayName = "Water Catcher Small", ShortName = "water.catcher.small", ItemId = -1342405573, Description = "Rain collector", StackSize = 1 },
            new() { DisplayName = "Water Catcher Large", ShortName = "water.catcher.large", ItemId = 173268132, Description = "Large rain collector", StackSize = 1 },
            new() { DisplayName = "Water Pump", ShortName = "water.pump", ItemId = 2088353346, Description = "Water extraction", StackSize = 1 },
            new() { DisplayName = "Water Purifier", ShortName = "water.purifier", ItemId = 1950721418, Description = "Water cleaning", StackSize = 1 },
            new() { DisplayName = "Fluid Switch & Pump", ShortName = "electric.fuelgenerator.small", ItemId = -1166712463, Description = "Fluid control", StackSize = 1 },
            new() { DisplayName = "Sprinkler", ShortName = "sprinkler", ItemId = -460592212, Description = "Plant watering", StackSize = 5 },

            // Farming
            new() { DisplayName = "Small Planter Box", ShortName = "planter.small", ItemId = 148953073, Description = "Small plant box", StackSize = 5 },
            new() { DisplayName = "Large Planter Box", ShortName = "planter.large", ItemId = 628019192, Description = "Large plant box", StackSize = 3 },
            new() { DisplayName = "Composter", ShortName = "composter", ItemId = 1921449233, Description = "Fertilizer maker", StackSize = 1 },
            new() { DisplayName = "Corn Seed", ShortName = "seed.corn", ItemId = 998894949, Description = "Corn seeds", StackSize = 50 },
            new() { DisplayName = "Hemp Seed", ShortName = "seed.hemp", ItemId = 583366917, Description = "Hemp seeds", StackSize = 50 },
            new() { DisplayName = "Potato Seed", ShortName = "seed.potato", ItemId = -961613995, Description = "Potato seeds", StackSize = 50 },
            new() { DisplayName = "Pumpkin Seed", ShortName = "seed.pumpkin", ItemId = -1511285251, Description = "Pumpkin seeds", StackSize = 50 },
            new() { DisplayName = "Berry Seeds", ShortName = "seed.red.berry", ItemId = -460592212, Description = "Berry seeds", StackSize = 50 },
            new() { DisplayName = "Horse Dung", ShortName = "horsedung", ItemId = -1712861680, Description = "Fertilizer", StackSize = 50 },
            new() { DisplayName = "Fertilizer", ShortName = "fertilizer", ItemId = -1623330855, Description = "Plant food", StackSize = 1000 },
            new() { DisplayName = "Clone", ShortName = "clone.hemp", ItemId = -307490664, Description = "Plant clone", StackSize = 10 },

            // Vehicles
            new() { DisplayName = "Kayak", ShortName = "kayak", ItemId = -1628526499, Description = "Small boat", StackSize = 1 },
            new() { DisplayName = "2 Man Horse Shovel", ShortName = "horse.shoes.basic", ItemId = 1989785143, Description = "Horse shoes", StackSize = 4 },
            new() { DisplayName = "Single Horse Saddle", ShortName = "horse.saddle.single", ItemId = 1989785143, Description = "Riding saddle", StackSize = 1 },
            new() { DisplayName = "Double Horse Saddle", ShortName = "horse.saddle.double", ItemId = 1989785143, Description = "Double saddle", StackSize = 1 },
            new() { DisplayName = "Armored Horse Armor", ShortName = "horse.armor.roadsign", ItemId = 1989785143, Description = "Horse armor", StackSize = 1 },
            new() { DisplayName = "Wooden Horse Armor", ShortName = "horse.armor.wood", ItemId = 1989785143, Description = "Wood horse armor", StackSize = 1 },
            new() { DisplayName = "Saddlebag", ShortName = "horse.saddlebag", ItemId = 1989785143, Description = "Horse storage", StackSize = 1 },

            // Modular Car Parts
            new() { DisplayName = "Cockpit Vehicle Module", ShortName = "vehicle.module.cockpit", ItemId = 1414245162, Description = "Driver seat", StackSize = 1 },
            new() { DisplayName = "Cockpit With Engine Vehicle Module", ShortName = "vehicle.module.cockpit.with.engine", ItemId = -1615281216, Description = "Driver with engine", StackSize = 1 },
            new() { DisplayName = "Armored Cockpit Vehicle Module", ShortName = "vehicle.module.cockpit.armored", ItemId = -1615281216, Description = "Armored cockpit", StackSize = 1 },
            new() { DisplayName = "Engine Vehicle Module", ShortName = "vehicle.module.engine", ItemId = -1615281216, Description = "Engine module", StackSize = 1 },
            new() { DisplayName = "Flatbed Vehicle Module", ShortName = "vehicle.module.flatbed", ItemId = -1615281216, Description = "Flatbed storage", StackSize = 1 },
            new() { DisplayName = "Fuel Tank Vehicle Module", ShortName = "vehicle.module.fuel.tank", ItemId = -1615281216, Description = "Fuel tank", StackSize = 1 },
            new() { DisplayName = "Large Flatbed Vehicle Module", ShortName = "vehicle.module.flatbed.large", ItemId = -1615281216, Description = "Large flatbed", StackSize = 1 },
            new() { DisplayName = "Passenger Vehicle Module", ShortName = "vehicle.module.passengers", ItemId = -1615281216, Description = "Passenger seats", StackSize = 1 },
            new() { DisplayName = "Rear Seats Vehicle Module", ShortName = "vehicle.module.rear.passengers", ItemId = -1615281216, Description = "Rear seats", StackSize = 1 },
            new() { DisplayName = "Storage Vehicle Module", ShortName = "vehicle.module.storage", ItemId = -1615281216, Description = "Storage module", StackSize = 1 },
            new() { DisplayName = "Taxi Vehicle Module", ShortName = "vehicle.module.taxi", ItemId = -1615281216, Description = "Taxi seats", StackSize = 1 },

            // Vehicle Parts
            new() { DisplayName = "Engine - 1 Valve", ShortName = "engine.part.valve1", ItemId = -1615281216, Description = "Basic engine", StackSize = 1 },
            new() { DisplayName = "Engine - 2 Valve", ShortName = "engine.part.valve2", ItemId = -1615281216, Description = "Medium engine", StackSize = 1 },
            new() { DisplayName = "Engine - 3 Valve", ShortName = "engine.part.valve3", ItemId = -1615281216, Description = "Advanced engine", StackSize = 1 },
            new() { DisplayName = "Piston", ShortName = "engine.part.piston", ItemId = -1615281216, Description = "Engine piston", StackSize = 1 },
            new() { DisplayName = "Crankshaft", ShortName = "engine.part.crankshaft", ItemId = -1615281216, Description = "Engine crankshaft", StackSize = 1 },
            new() { DisplayName = "Spark Plug", ShortName = "engine.part.sparkplug", ItemId = -1615281216, Description = "Engine spark plug", StackSize = 1 },
            new() { DisplayName = "Carburetor", ShortName = "engine.part.carburetor", ItemId = -1615281216, Description = "Engine carburetor", StackSize = 1 },

            // Signs
            new() { DisplayName = "Wooden Sign", ShortName = "sign.wooden.small", ItemId = 1628490888, Description = "Small sign", StackSize = 1 },
            new() { DisplayName = "Large Wooden Sign", ShortName = "sign.wooden.large", ItemId = 846607281, Description = "Large sign", StackSize = 1 },
            new() { DisplayName = "Huge Wooden Sign", ShortName = "sign.wooden.huge", ItemId = -520133715, Description = "Huge sign", StackSize = 1 },
            new() { DisplayName = "Two Sided Hanging Sign", ShortName = "sign.hanging", ItemId = 1376065505, Description = "Hanging sign", StackSize = 1 },
            new() { DisplayName = "Landscape Picture Frame", ShortName = "sign.pictureframe.landscape", ItemId = 385802761, Description = "Wide picture frame", StackSize = 1 },
            new() { DisplayName = "Portrait Picture Frame", ShortName = "sign.pictureframe.portrait", ItemId = -1455694274, Description = "Tall picture frame", StackSize = 1 },
            new() { DisplayName = "Tall Picture Frame", ShortName = "sign.pictureframe.tall", ItemId = -282113991, Description = "Very tall frame", StackSize = 1 },
            new() { DisplayName = "XL Picture Frame", ShortName = "sign.pictureframe.xl", ItemId = -790519001, Description = "Extra large frame", StackSize = 1 },
            new() { DisplayName = "XXL Picture Frame", ShortName = "sign.pictureframe.xxl", ItemId = -1722829188, Description = "Huge frame", StackSize = 1 },
            new() { DisplayName = "Sign Post", ShortName = "sign.post.single", ItemId = 1957158128, Description = "Single post sign", StackSize = 1 },
            new() { DisplayName = "Double Sign Post", ShortName = "sign.post.double", ItemId = 634236516, Description = "Double post sign", StackSize = 1 },
            new() { DisplayName = "Town Sign Post", ShortName = "sign.post.town", ItemId = 2123300234, Description = "Town sign", StackSize = 1 },
            new() { DisplayName = "One Sided Town Sign Post", ShortName = "sign.post.town.roof", ItemId = 1498516223, Description = "Roof sign", StackSize = 1 },
            new() { DisplayName = "Banner on Pole", ShortName = "sign.hanging.banner.large", ItemId = 2100007442, Description = "Large banner", StackSize = 1 },
            new() { DisplayName = "Neon Sign", ShortName = "sign.neon.xl", ItemId = -1224598842, Description = "Neon light sign", StackSize = 1 },

            // Instruments
            new() { DisplayName = "Acoustic Guitar", ShortName = "fun.guitar", ItemId = -1461508848, Description = "Musical instrument", StackSize = 1 },
            new() { DisplayName = "Jerry Can Guitar", ShortName = "fun.jerrycanguitar", ItemId = -695978112, Description = "Makeshift guitar", StackSize = 1 },
            new() { DisplayName = "Canbourine", ShortName = "fun.tambourine", ItemId = 1973684065, Description = "Percussion instrument", StackSize = 1 },
            new() { DisplayName = "Cowbell", ShortName = "fun.cowbell", ItemId = 1789825282, Description = "Percussion instrument", StackSize = 1 },
            new() { DisplayName = "Junkyard Drum Kit", ShortName = "drumkit", ItemId = -695978112, Description = "Drum set", StackSize = 1 },
            new() { DisplayName = "Pan Flute", ShortName = "fun.flute", ItemId = 1414245162, Description = "Wind instrument", StackSize = 1 },
            new() { DisplayName = "Piano", ShortName = "piano", ItemId = -1615281216, Description = "Piano instrument", StackSize = 1 },
            new() { DisplayName = "Shovel Bass", ShortName = "fun.bass", ItemId = -695978112, Description = "Bass instrument", StackSize = 1 },
            new() { DisplayName = "Sousaphone", ShortName = "fun.tuba", ItemId = -1389867269, Description = "Brass instrument", StackSize = 1 },
            new() { DisplayName = "Trumpet", ShortName = "fun.trumpet", ItemId = 1849912854, Description = "Brass instrument", StackSize = 1 },
            new() { DisplayName = "Xylophone", ShortName = "xylophone", ItemId = -1615281216, Description = "Percussion instrument", StackSize = 1 },
            new() { DisplayName = "Wheelbarrow Piano", ShortName = "wheelbarrowpiano", ItemId = -1615281216, Description = "Mobile piano", StackSize = 1 },
            new() { DisplayName = "Microphone Stand", ShortName = "microphonestand", ItemId = 196700171, Description = "Microphone holder", StackSize = 1 },
            new() { DisplayName = "Connected Speaker", ShortName = "connectedspeaker", ItemId = -139187866, Description = "Audio output", StackSize = 1 },
            new() { DisplayName = "Disco Ball", ShortName = "discoball", ItemId = -804935631, Description = "Disco light", StackSize = 1 },
            new() { DisplayName = "Disco Floor", ShortName = "discofloor", ItemId = -2090395734, Description = "Dance floor", StackSize = 1 },
            new() { DisplayName = "Disco Floor Tile", ShortName = "discofloor.largetile", ItemId = -1409578938, Description = "Floor tile", StackSize = 1 },

            // Decorations
            new() { DisplayName = "Small Rug", ShortName = "rug", ItemId = 62577426, Description = "Floor covering", StackSize = 5 },
            new() { DisplayName = "Bear Rug", ShortName = "rug.bear", ItemId = -1732316031, Description = "Bear skin rug", StackSize = 1 },
            new() { DisplayName = "Christmas Tree", ShortName = "xmas.tree", ItemId = 174866732, Description = "Holiday decoration", StackSize = 1 },
            new() { DisplayName = "Skull Trophy", ShortName = "skulltrophy", ItemId = 1891056868, Description = "Skull display", StackSize = 1 },
            new() { DisplayName = "Trophy", ShortName = "trophy", ItemId = -1999789428, Description = "Trophy display", StackSize = 1 },
            new() { DisplayName = "Photo Frame", ShortName = "photoframe.large", ItemId = 2122716895, Description = "Large photo", StackSize = 1 },
            new() { DisplayName = "Small Candle Set", ShortName = "smallcandles", ItemId = 699075597, Description = "Candle set", StackSize = 3 },
            new() { DisplayName = "Tall Candle Set", ShortName = "candlehat", ItemId = 699075597, Description = "Candle set", StackSize = 3 },
            new() { DisplayName = "Spider Webs", ShortName = "spiderweb", ItemId = 1414245162, Description = "Decoration", StackSize = 10 },
            new() { DisplayName = "Scarecrow", ShortName = "scarecrow", ItemId = -134681453, Description = "Decoration", StackSize = 1 },
            new() { DisplayName = "Strobe Light", ShortName = "strobelight", ItemId = 286648290, Description = "Flashing light", StackSize = 3 },
            new() { DisplayName = "Fogger-3000", ShortName = "fogmachine", ItemId = 696727039, Description = "Fog machine", StackSize = 1 },
            new() { DisplayName = "Snow Machine", ShortName = "snowmachine", ItemId = 1358643074, Description = "Snow maker", StackSize = 1 },
            new() { DisplayName = "Gravestone", ShortName = "gravestone", ItemId = -1588628467, Description = "Grave marker", StackSize = 1 },
            new() { DisplayName = "Skull Door Knocker", ShortName = "skulldoorknocker", ItemId = 1763201594, Description = "Door decoration", StackSize = 1 },
            new() { DisplayName = "Wooden Frontier Bar", ShortName = "woodenbar", ItemId = -1478212975, Description = "Bar furniture", StackSize = 1 },
            new() { DisplayName = "Xylobone", ShortName = "fun.xylobones", ItemId = 1917703890, Description = "Bone xylophone", StackSize = 1 },
            new() { DisplayName = "Frankenstein Table", ShortName = "frankensteintable", ItemId = 838308300, Description = "Table decoration", StackSize = 1 },

            // Furniture
            new() { DisplayName = "Chair", ShortName = "chair", ItemId = 1524980732, Description = "Seating", StackSize = 1 },
            new() { DisplayName = "Sofa", ShortName = "sofa", ItemId = -1607980696, Description = "Large seating", StackSize = 1 },
            new() { DisplayName = "Table", ShortName = "table", ItemId = -1601468835, Description = "Furniture", StackSize = 1 },
            new() { DisplayName = "Spinning Wheel", ShortName = "spinner.wheel", ItemId = 1660607208, Description = "Spinning game", StackSize = 1 },
            new() { DisplayName = "Slot Machine", ShortName = "slotmachine", ItemId = 313836902, Description = "Gambling machine", StackSize = 1 },
            new() { DisplayName = "Chippy Arcade Game", ShortName = "chippyarcade", ItemId = 2104517339, Description = "Arcade game", StackSize = 1 },
            new() { DisplayName = "Computer Station", ShortName = "computerstation", ItemId = -1588628467, Description = "CCTV viewer", StackSize = 1 },
            new() { DisplayName = "Vending Machine", ShortName = "vending.machine", ItemId = 186002280, Description = "Automated shop", StackSize = 1 },
            new() { DisplayName = "Shop Front", ShortName = "wall.frame.shopfront", ItemId = -357728804, Description = "Shop window", StackSize = 1 },
            new() { DisplayName = "Drop Box", ShortName = "dropbox", ItemId = -1621539785, Description = "Item drop box", StackSize = 1 },
            new() { DisplayName = "Mail Box", ShortName = "mailbox", ItemId = -2058362263, Description = "Mail storage", StackSize = 1 },

            // Attachments
            new() { DisplayName = "Weapon Flashlight", ShortName = "weapon.mod.flashlight", ItemId = -1379225193, Description = "Gun flashlight", StackSize = 1 },
            new() { DisplayName = "Weapon Lasersight", ShortName = "weapon.mod.lasersight", ItemId = -132516482, Description = "Gun laser", StackSize = 1 },
            new() { DisplayName = "Holosight", ShortName = "weapon.mod.holosight", ItemId = 442289265, Description = "Holographic sight", StackSize = 1 },
            new() { DisplayName = "Simple Handmade Sight", ShortName = "weapon.mod.simplesight", ItemId = -855748505, Description = "Basic sight", StackSize = 1 },
            new() { DisplayName = "4x Zoom Scope", ShortName = "weapon.mod.small.scope", ItemId = 567235583, Description = "4x magnification", StackSize = 1 },
            new() { DisplayName = "8x Zoom Scope", ShortName = "weapon.mod.8x.scope", ItemId = -1490658066, Description = "8x magnification", StackSize = 1 },
            new() { DisplayName = "16x Zoom Scope", ShortName = "weapon.mod.16x.scope", ItemId = -1850571427, Description = "16x magnification", StackSize = 1 },
            new() { DisplayName = "Silencer", ShortName = "weapon.mod.silencer", ItemId = -1850571427, Description = "Noise reduction", StackSize = 1 },
            new() { DisplayName = "Muzzle Boost", ShortName = "weapon.mod.muzzleboost", ItemId = -1850571427, Description = "Fire rate boost", StackSize = 1 },
            new() { DisplayName = "Muzzle Brake", ShortName = "weapon.mod.muzzlebrake", ItemId = -1850571427, Description = "Recoil reduction", StackSize = 1 },
            new() { DisplayName = "Extended Magazine", ShortName = "weapon.mod.extendedmags", ItemId = -1850571427, Description = "Extra ammo", StackSize = 1 },

            // Misc
            new() { DisplayName = "Note", ShortName = "note", ItemId = 1414245162, Description = "Written note", StackSize = 1 },
            new() { DisplayName = "Paper", ShortName = "paper", ItemId = 1414245162, Description = "Blank paper", StackSize = 100 },
            new() { DisplayName = "Map", ShortName = "map", ItemId = 1414245162, Description = "Area map", StackSize = 1 },
            new() { DisplayName = "Camera", ShortName = "tool.camera", ItemId = 1424075905, Description = "Photo camera", StackSize = 1 },
            new() { DisplayName = "Cassette (Long)", ShortName = "cassette", ItemId = -2107018088, Description = "Audio recording", StackSize = 1 },
            new() { DisplayName = "Cassette (Medium)", ShortName = "cassette.medium", ItemId = -1455694274, Description = "Audio recording", StackSize = 1 },
            new() { DisplayName = "Cassette (Short)", ShortName = "cassette.short", ItemId = -282113991, Description = "Audio recording", StackSize = 1 },
            new() { DisplayName = "Cassette Recorder", ShortName = "cassette.recorder", ItemId = 634236516, Description = "Audio player", StackSize = 1 },
            new() { DisplayName = "Portable Boom Box", ShortName = "boombox.portable", ItemId = -2094954543, Description = "Music player", StackSize = 1 },
            new() { DisplayName = "Telephone", ShortName = "telephone", ItemId = 1058261682, Description = "Communication", StackSize = 1 },
            new() { DisplayName = "Firework", ShortName = "firework.boomer.blue", ItemId = -1832422579, Description = "Blue firework", StackSize = 10 },
            new() { DisplayName = "Red Firework", ShortName = "firework.boomer.red", ItemId = 1324203999, Description = "Red firework", StackSize = 10 },
            new() { DisplayName = "Green Firework", ShortName = "firework.boomer.green", ItemId = -1040518150, Description = "Green firework", StackSize = 10 },
            new() { DisplayName = "Orange Firework", ShortName = "firework.boomer.orange", ItemId = -514312476, Description = "Orange firework", StackSize = 10 },
            new() { DisplayName = "Violet Firework", ShortName = "firework.boomer.violet", ItemId = 1491189398, Description = "Purple firework", StackSize = 10 },
            new() { DisplayName = "Smoke Grenade", ShortName = "grenade.smoke", ItemId = 915408809, Description = "Creates smoke", StackSize = 5 },
            new() { DisplayName = "Flare", ShortName = "flare", ItemId = 1523195708, Description = "Light signal", StackSize = 10 },
            new() { DisplayName = "Blue Keycard", ShortName = "keycard_blue", ItemId = -484206264, Description = "Access card", StackSize = 1 },
            new() { DisplayName = "Green Keycard", ShortName = "keycard_green", ItemId = 37122747, Description = "Access card", StackSize = 1 },
            new() { DisplayName = "Red Keycard", ShortName = "keycard_red", ItemId = -1880870149, Description = "Access card", StackSize = 1 },
            new() { DisplayName = "Electric Fuse", ShortName = "fuse", ItemId = -1732475823, Description = "Electric component", StackSize = 5 },
            new() { DisplayName = "Human Skull", ShortName = "skull.human", ItemId = 1351172108, Description = "Human skull", StackSize = 1 },
            new() { DisplayName = "Wolf Skull", ShortName = "skull.wolf", ItemId = -1992717673, Description = "Wolf skull", StackSize = 1 },

            // Tea Items
            new() { DisplayName = "Advanced Healing Tea", ShortName = "healingtea.advanced", ItemId = -1157596551, Description = "Strong healing", StackSize = 10 },
            new() { DisplayName = "Basic Healing Tea", ShortName = "healingtea", ItemId = -1157596551, Description = "Basic healing", StackSize = 10 },
            new() { DisplayName = "Pure Healing Tea", ShortName = "healingtea.pure", ItemId = -1157596551, Description = "Best healing", StackSize = 10 },
            new() { DisplayName = "Advanced Max Health Tea", ShortName = "maxhealthtea.advanced", ItemId = -1157596551, Description = "Strong max health", StackSize = 10 },
            new() { DisplayName = "Basic Max Health Tea", ShortName = "maxhealthtea", ItemId = -1157596551, Description = "Basic max health", StackSize = 10 },
            new() { DisplayName = "Pure Max Health Tea", ShortName = "maxhealthtea.pure", ItemId = -1157596551, Description = "Best max health", StackSize = 10 },
            new() { DisplayName = "Advanced Ore Tea", ShortName = "oretea.advanced", ItemId = -1157596551, Description = "Strong ore bonus", StackSize = 10 },
            new() { DisplayName = "Basic Ore Tea", ShortName = "oretea", ItemId = -1157596551, Description = "Basic ore bonus", StackSize = 10 },
            new() { DisplayName = "Pure Ore Tea", ShortName = "oretea.pure", ItemId = -1157596551, Description = "Best ore bonus", StackSize = 10 },
            new() { DisplayName = "Advanced Scrap Tea", ShortName = "scraptea.advanced", ItemId = -1157596551, Description = "Strong scrap bonus", StackSize = 10 },
            new() { DisplayName = "Basic Scrap Tea", ShortName = "scraptea", ItemId = -1157596551, Description = "Basic scrap bonus", StackSize = 10 },
            new() { DisplayName = "Pure Scrap Tea", ShortName = "scraptea.pure", ItemId = -1157596551, Description = "Best scrap bonus", StackSize = 10 },
            new() { DisplayName = "Advanced Wood Tea", ShortName = "woodtea.advanced", ItemId = -1157596551, Description = "Strong wood bonus", StackSize = 10 },
            new() { DisplayName = "Basic Wood Tea", ShortName = "woodtea", ItemId = -1157596551, Description = "Basic wood bonus", StackSize = 10 },
            new() { DisplayName = "Pure Wood Tea", ShortName = "woodtea.pure", ItemId = -1157596551, Description = "Best wood bonus", StackSize = 10 },
            new() { DisplayName = "Advanced Rad Removal Tea", ShortName = "radiationremovetea.advanced", ItemId = -1157596551, Description = "Strong rad removal", StackSize = 10 },
            new() { DisplayName = "Basic Rad Removal Tea", ShortName = "radiationremovetea", ItemId = -1157596551, Description = "Basic rad removal", StackSize = 10 },
            new() { DisplayName = "Pure Rad Removal Tea", ShortName = "radiationremovetea.pure", ItemId = -1157596551, Description = "Best rad removal", StackSize = 10 },
            new() { DisplayName = "Advanced Anti-Rad Tea", ShortName = "radiationresisttea.advanced", ItemId = -1157596551, Description = "Strong rad resist", StackSize = 10 },
            new() { DisplayName = "Basic Anti-Rad Tea", ShortName = "radiationresisttea", ItemId = -1157596551, Description = "Basic rad resist", StackSize = 10 },
            new() { DisplayName = "Pure Anti-Rad Tea", ShortName = "radiationresisttea.pure", ItemId = -1157596551, Description = "Best rad resist", StackSize = 10 },
        };
    }
}
