// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RustRconServerManager.Backend.Database;

#nullable disable

namespace RustRconServerManager.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.AggregatedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregationType")
                        .HasColumnType("int");

                    b.Property<double?>("Avg")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Max")
                        .HasColumnType("double");

                    b.Property<double?>("Min")
                        .HasColumnType("double");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Stat", "Timestamp", "AggregationType");

                    b.ToTable("AggregatedStats");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiscordId")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nickname")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("SelectedServerId")
                        .HasColumnType("int");

                    b.Property<string>("SessionHash")
                        .HasColumnType("longtext");

                    b.Property<string>("SteamId")
                        .HasColumnType("longtext");

                    b.Property<int>("SystemProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Website")
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isLoginBlocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SystemProfileId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerName")
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.DeveloperVacBanOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DaysSinceLastBan")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfVACBans")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("VACBanned")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SteamId")
                        .IsUnique();

                    b.ToTable("DeveloperVacBanOverrides");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.DevicePushToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DevicePushTokens");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.IpVpnCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsVpn")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProxyType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("IpVpnCache");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.LegalConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("AcceptedPrivacyPolicy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcceptedTermsAndConditions")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConsentAnonymousMetrics")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("PrivacyVersion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TermsVersion")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LegalConsents");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.MapData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("int");

                    b.Property<int?>("MapSeed")
                        .HasColumnType("int");

                    b.Property<int?>("MapSize")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("MapData");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ModeratorPagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PageRoute")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PageRoute")
                        .IsUnique();

                    b.ToTable("ModeratorPagePermissions");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ModeratorServerPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RconServerId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RconServerId");

                    b.HasIndex("UserId", "RconServerId")
                        .IsUnique();

                    b.ToTable("ModeratorServerPermissions");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PanelSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoUpdateEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DeveloperModeEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MinimumLogLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SystemProfileId")
                        .HasColumnType("int");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SystemProfileId")
                        .IsUnique();

                    b.ToTable("PanelSettings");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("Expiry")
                        .HasColumnType("bigint");

                    b.Property<string>("Group")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalNote")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGlobalBan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLifted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LiftedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LiftedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlayerBans");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerBanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BannedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("DurationHours")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsGlobalBan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LiftReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LiftedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LiftedBy")
                        .HasColumnType("longtext");

                    b.Property<int?>("PlayerBanId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PlayerBanHistories");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerIpHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FirstUsed")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsVpn")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SteamId", "ServerId");

                    b.HasIndex("SteamId", "ServerId", "IpAddress")
                        .IsUnique();

                    b.ToTable("PlayerIpHistory");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerKillLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPVP")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KilledById")
                        .HasColumnType("longtext");

                    b.Property<string>("KilledByName")
                        .HasColumnType("longtext");

                    b.Property<string>("KilledPlayerId")
                        .HasColumnType("longtext");

                    b.Property<string>("KilledPlayerName")
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlayerKillLogs");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(17)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PlayerNotes");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ReportedId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReportedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("PlayerReports");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PluginVersionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PluginUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<int?>("UmodRateLimitRemaining")
                        .HasColumnType("int");

                    b.Property<int?>("UmodRateLimitTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PluginName");

                    b.ToTable("PluginVersionCache");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PresetCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RconServerId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RconServerId");

                    b.ToTable("PresetCommands");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.RconLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RconLogEntries");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.RconServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedHost")
                        .HasColumnType("longtext");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("EnvironmentSecret")
                        .HasColumnType("longtext");

                    b.Property<int?>("GamePort")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LatestEntityCount")
                        .HasColumnType("int");

                    b.Property<int?>("LatestFpsCount")
                        .HasColumnType("int");

                    b.Property<int?>("LatestJoiningPlayers")
                        .HasColumnType("int");

                    b.Property<string>("LatestMap")
                        .HasColumnType("longtext");

                    b.Property<int?>("LatestMemoryUsage")
                        .HasColumnType("int");

                    b.Property<int?>("LatestPlayerCount")
                        .HasColumnType("int");

                    b.Property<int?>("LatestQueuedPlayers")
                        .HasColumnType("int");

                    b.Property<string>("LatestServerProtocol")
                        .HasColumnType("longtext");

                    b.Property<int?>("LatestServerVersion")
                        .HasColumnType("int");

                    b.Property<int?>("LatestUptime")
                        .HasColumnType("int");

                    b.Property<string>("ModFramework")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QueryPort")
                        .HasColumnType("int");

                    b.Property<int>("RconPort")
                        .HasColumnType("int");

                    b.Property<bool>("RrsmModInitialized")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RustRconServerManagerModInstalled")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte[]>("ServerHeaderImageData")
                        .HasColumnType("longblob");

                    b.Property<string>("ServerHostname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("ServerLogoImageData")
                        .HasColumnType("longblob");

                    b.Property<int>("SystemProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemProfileId");

                    b.ToTable("RconServers");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.RustItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StackSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RustItems");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ScheduledCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExecuteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExecutionCount")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutionHour")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutionMinute")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalHours")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastExecutionError")
                        .HasColumnType("longtext");

                    b.Property<bool?>("LastExecutionSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NextExecutionAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RconServerId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UtcOffsetMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RconServerId");

                    b.ToTable("ScheduledCommands");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerPluginSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RustServerId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RustServerId", "PluginName")
                        .IsUnique();

                    b.ToTable("ServerPluginSources");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerProtectionSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("BlockPrivateSteamProfiles")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CountryFilterMode")
                        .HasColumnType("int");

                    b.Property<string>("CountryList")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnablePublicBanProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableVacBanProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableVpnCheck")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableVpnProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableWhitelistOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxPublicBans")
                        .HasColumnType("int");

                    b.Property<int>("MaxVacBans")
                        .HasColumnType("int");

                    b.Property<int>("MinDaysSinceLastVACBan")
                        .HasColumnType("int");

                    b.Property<int>("PrivateSteamProfileAction")
                        .HasColumnType("int");

                    b.Property<int>("PublicBanAction")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VacBanAction")
                        .HasColumnType("int");

                    b.Property<int>("VpnProtectionAction")
                        .HasColumnType("int");

                    b.Property<string>("WhitelistOnlyKickMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhitelistedSteamIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerProtectionSettings");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerWebhookSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnablePlayerBanWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePlayerConnectWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePlayerDisconnectWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePlayerKickWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePlayerKillWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePlayerReportWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableServerOfflineWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableServerOnlineWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableServerProtectionWebhook")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PlayerBanCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerBanFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerBanTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerBanWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerConnectCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerConnectFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerConnectTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerConnectWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerDisconnectCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerDisconnectFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerDisconnectTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerDisconnectWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerKickCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerKickFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerKickTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerKickWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerKillCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerKillFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerKillTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerKillWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerReportCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PlayerReportFormat")
                        .HasColumnType("int");

                    b.Property<string>("PlayerReportTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerReportWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("ServerOfflineCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerOfflineFormat")
                        .HasColumnType("int");

                    b.Property<string>("ServerOfflineTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerOfflineWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerOnlineCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerOnlineFormat")
                        .HasColumnType("int");

                    b.Property<string>("ServerOnlineTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerOnlineWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerProtectionCustomContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ServerProtectionFormat")
                        .HasColumnType("int");

                    b.Property<string>("ServerProtectionTextContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServerProtectionWebhookUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerWebhookSettings");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.SleepingBagData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerSteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("PositionX")
                        .HasColumnType("float");

                    b.Property<float>("PositionY")
                        .HasColumnType("float");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("SleepingBags");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.StatsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Stat", "CreatedAt");

                    b.ToTable("StatsHistories");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.SteamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AvatarLastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DaysSinceLastVACBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("LatestHealth")
                        .HasColumnType("float");

                    b.Property<int?>("LatestPing")
                        .HasColumnType("int");

                    b.Property<float?>("LatestPositionX")
                        .HasColumnType("float");

                    b.Property<float?>("LatestPositionY")
                        .HasColumnType("float");

                    b.Property<float?>("LatestPositionZ")
                        .HasColumnType("float");

                    b.Property<int?>("LatestTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumberOfVACBans")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileVisibility")
                        .HasColumnType("int");

                    b.Property<int?>("RustPlaytimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SteamAccountCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("VACBanned")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("SteamPlayers");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.SystemProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SystemProfiles");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ToolCupboardData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedPlayers")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerSteamId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("PositionX")
                        .HasColumnType("float");

                    b.Property<float>("PositionY")
                        .HasColumnType("float");

                    b.Property<float>("PositionZ")
                        .HasColumnType("float");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ToolCupboards");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.Trigger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ChatConditionType")
                        .HasColumnType("longtext");

                    b.Property<string>("ChatConditionValue")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastExecutionError")
                        .HasColumnType("longtext");

                    b.Property<bool?>("LastExecutionSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RconServerId")
                        .HasColumnType("int");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("int");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RconServerId");

                    b.ToTable("Triggers");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.UserNotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("PlayerBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PlayerOffline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PlayerOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PlayerReported")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<bool>("ServerOffline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ServerOnline")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ServerProtection")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId", "ServerId")
                        .IsUnique();

                    b.ToTable("UserNotificationPreferences");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRevoked");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ApplicationUser", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.SystemProfile", "SystemProfile")
                        .WithMany()
                        .HasForeignKey("SystemProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemProfile");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.DevicePushToken", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.LegalConsent", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.MapData", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "Server")
                        .WithOne()
                        .HasForeignKey("RustRconServerManager.Backend.Models.MapData", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ModeratorPagePermission", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany("PagePermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ModeratorServerPermission", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "RconServer")
                        .WithMany("ModeratorPermissions")
                        .HasForeignKey("RconServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany("ServerPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RconServer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PanelSettings", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.SystemProfile", "SystemProfile")
                        .WithOne("PanelSettings")
                        .HasForeignKey("RustRconServerManager.Backend.Models.PanelSettings", "SystemProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemProfile");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PlayerReport", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.PresetCommand", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "RconServer")
                        .WithMany()
                        .HasForeignKey("RconServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RconServer");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.RconServer", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.SystemProfile", "SystemProfile")
                        .WithMany()
                        .HasForeignKey("SystemProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemProfile");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ScheduledCommand", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "RconServer")
                        .WithMany()
                        .HasForeignKey("RconServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RconServer");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerPluginSource", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "RconServer")
                        .WithMany()
                        .HasForeignKey("RustServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RconServer");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerProtectionSettings", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ServerWebhookSettings", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.Trigger", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "RconServer")
                        .WithMany()
                        .HasForeignKey("RconServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RconServer");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.UserNotificationPreference", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.RconServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.UserSession", b =>
                {
                    b.HasOne("RustRconServerManager.Backend.Models.ApplicationUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.ApplicationUser", b =>
                {
                    b.Navigation("PagePermissions");

                    b.Navigation("ServerPermissions");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.RconServer", b =>
                {
                    b.Navigation("ModeratorPermissions");
                });

            modelBuilder.Entity("RustRconServerManager.Backend.Models.SystemProfile", b =>
                {
                    b.Navigation("PanelSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
